### ISSUE TITLE
Multi subscription end point 

### ISSUE THREAD

**Issue by AhmadEl-Banna** [habx/apollo-multi-endpoint-link#156]
Hi, I got multiple Graphql servers, and everyone has their own subscriptions
I'm wondering if your middleware support that or willing to support it in the near future?

**Comment by jean9696** [comment]
@AhmadEl-Banna It totally supports it 👍 
Here is an example of configuration with subscriptions
```ts
      new MultiAPILink({
        endpoints,
        wsSuffix: '/graphql/subscriptions',
        createWsLink: (uri) =>
          new WebSocketLink({
            uri,
          }),
        createHttpLink: () =>
          new HttpLink({
            credentials:
              window.HABX_ENV === 'local' ? 'include' : 'same-origin',
            headers: {
              'X-Request-From': clients.cms.name,
            },
          }),
      }),
```

**Comment by chipcop106** [comment]
> @AhmadEl-Banna It totally supports it 👍 Here is an example of configuration with subscriptions
> 
> ```ts
>       new MultiAPILink({
>         endpoints,
>         wsSuffix: '/graphql/subscriptions',
>         createWsLink: (uri) =>
>           new WebSocketLink({
>             uri,
>           }),
>         createHttpLink: () =>
>           new HttpLink({
>             credentials:
>               window.HABX_ENV === 'local' ? 'include' : 'same-origin',
>             headers: {
>               'X-Request-From': clients.cms.name,
>             },
>           }),
>       }),
> ```
"URI" argument got value undefined
