### ISSUE TITLE
Default endpoint

### ISSUE THREAD

**Issue by davidpenso** [habx/apollo-multi-endpoint-link#171]
Is there a way to define a default endpoint? So if `{ context: { apiName: 'name' } }` is not passed it defaults to that endpoint?

**Comment by jean9696** [comment]
Hi @davidpenso, we did not implement such a thing for now. 

We preferred to set the endpoint explicitly for every query to avoid mistakes. But you are welcome to make a PR to implement this behaviour with an optional param in the link 🙂

**Comment by Carolinevp** [comment]
@davidpenso it's done [here](https://github.com/habx/apollo-multi-endpoint-link/pull/277)
