### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by mwoodpatrick** [habx/apollo-multi-endpoint-link#194]
Looks like tscov is missing from dev dependencies

Adding this and running

npm run type:coverage

shows error

Error: ENOENT: no such file or directory, stat '/home/mwoodpatrick/projects/git/www/apollo-multi-endpoint-link/@habx/config-ci-front/typescript/library.json'

**Comment by jean9696** [comment]
Hi @mwoodpatrick,
We didn't intend to manage it. [I removed it ](https://github.com/habx/apollo-multi-endpoint-link/pull/195)but if you find a way to fix it, PRs are welcome :)
