### ISSUE TITLE
How to pass additional variables to query?

### ISSUE THREAD

**Issue by husman** [habx/apollo-multi-endpoint-link#282]
Great idea to put together this library! I know the library is pretty young, and thus the documentation is lacking. I was wondering how we can pass in additional parameters/variables to the query?

**Comment by husman** [comment]
Nevermind figured it out.

E.g.
```
query myQuery(
  $var1: String,
  $var2: String,
) @api(name: projects) {
    myQuery(
        var1: $var1,
        var2: $var2,
    ) {
        field1 {
            subField1
            subField2
        }
        field2
    }
}
```

**Comment by jean9696** [comment]
Hi @husman, how could we improve the documentation for what you needed ? 
For what I understand, it's just a regular query. The library is just adding a [directive](http://spec.graphql.org/June2018/#sec-Type-System.Directives)

**Comment by jean9696** [comment]
I made one small change [here](https://github.com/habx/apollo-multi-endpoint-link/pull/283)

**Comment by husman** [comment]
Sorry for the delay. I was about to submit a PR to update the README, but it looks like @jean9696 beat me to it. Thank you @jean9696!

**Comment by husman** [comment]
Fixed by https://github.com/habx/apollo-multi-endpoint-link/pull/283
