### ISSUE TITLE
Mulitple Apis in a single query

### ISSUE THREAD

**Issue by thirdcreed** [habx/apollo-multi-endpoint-link#293]
How can I use two different apis in a single query, is there anyway to make api directives subquery specific?

```
  query($id: String!) {
    widgets( id: $id ) @api(name: widgetEndpoint) {
      width
      weight
    }
    gadgets( id: $id ) @api(name: gadgetEndpoint) {
      length
      color
    }
  }
;
```

**Comment by jean9696** [comment]
Hi @thirdcreed, for now we do not manage this case as it would mean that the client would have to send 2 requests and merge them later when responses come back.

**Comment by thirdcreed** [comment]
Ok, thank you.
