### ISSUE TITLE
api directive not acceptable by server side and how can define it in the backend

### ISSUE THREAD

**Issue by Abdulrahmanelheyb** [habx/apollo-multi-endpoint-link#392]
Hi, I am using WebStorm with the GraphQL extension. Intellisense gives me an error when I add API Directive, How can solve this problem, I tried to search how to add a directive to the nest.js with the arguments but I don't find a solution

**Comment by jean9696** [comment]
Hi @Abdulrahmanelheyb, this is not related to the link we provide. You need to add your custom directives to the schema definition. I don't know how you generate it ?
