### ISSUE TITLE
Endpoints get messed up when querying with a unique @api name

### ISSUE THREAD

**Issue by 0xpolarzero** [habx/apollo-multi-endpoint-link#395]
Hi there,

I'm running into an issue with the `apollo-multi-endpoint-link`, and at this point I have no idea what to do anymore.

I'm using the same configuration as the example, providing 3 different endpoints, and using 3 Graphql queries that use this name as an identifier. Like this:

Queries:
```javascript
const GET_ACTIVE_ITEMS_GOERLI = gql`
  query GetActiveItems @api(name: goerli) {
    activeItems(
...
`
const GET_ACTIVE_ITEMS_MUMBAI = gql`
  query GetActiveItems @api(name: mumbai) {
...
`
const GET_ACTIVE_ITEMS_ARBITRUM_GOERLI = gql`
  query GetActiveItems @api(name: arbitrumGoerli) {
...
`
```

Fetching:
```javascript
const { data: goerliData, loading: goerliDataLoading } = useQuery(
    GET_ACTIVE_ITEMS_GOERLI,
  );
  const { data: mumbaiData, loading: mumbaiDataLoading } = useQuery(
    GET_ACTIVE_ITEMS_MUMBAI,
  );
  const { data: arbitrumGoerliData, loading: arbitrumGoerliDataLoading } =
    useQuery(GET_ACTIVE_ITEMS_ARBITRUM_GOERLI);
```

Configuration:
```javascript
const apolloClient = new ApolloClient({
  cache: new InMemoryCache(),
  link: ApolloLink.from([
    errorLink,
    new MultiAPILink({
      endpoints: {
        goerli: process.env.NEXT_PUBLIC_SUBGRAPH_URL_GOERLI,
        mumbai: process.env.NEXT_PUBLIC_SUBGRAPH_URL_MUMBAI,
        arbitrumGoerli: process.env.NEXT_PUBLIC_SUBGRAPH_URL_ARBITRUM_GOERLI,
      },
      createHttpLink: () => createHttpLink(),
      httpSuffix: '',
    }),
  ]),
});
```

These queries are all fetched, then a `useEffect` hook sets a new variable `activeItems`, choosing from the 3 results based on the network.

Unfortunatly, the `activeItems` result seems completely random, as passing one network name will make the variable change between the queries results with no regularity. All 3 data variables `goerliData` `mumbaiData` and `arbitrumGoerliData` get initialized with the same array on each refresh, as if the 3 query results could not coexist.

Since the network and conditions are working correctly, I believe the `@api(name)` selector is not working. It looks like it's setting `activeItems` to one of the 3 queries without respecting the endpoint selection.

I have no idea what I'm doing wrong here. Here is a codesandbox with just the needed parameters. 
You can start it as usual `yarn && yarn dev`, go to `index.js` <s>and then just change the `network` variable (line 63) to any of the 3 networks: `goerli` / `mumbai` / `arbitrumGoerli`. Then you just refresh the page. And you can repeat. They should respectively return an array of 9 / 2 / 4 objects, but they don't.</s> Actually, you just need to refresh the page a few times, the results will change sometimes, maybe because it gets set up to the latest query result ? Although each data should get its own query ?

https://codesandbox.io/s/multi-endpoints-issue-dzxdw7?file=/pages/index.js

Thanks already to anyone who will take the time to help me :)

**Comment by 0xpolarzero** [comment]
Absolutely my mistake here, and it is completely related to @apollo/client. Here is what I think happened, from my novice perspective. And a better solution, not great though, it is not yet working as I expected.

I guess the `useQuery` hook can't perform several queries simultaneously, since they're all going into the same pipeline. So in my case, I'm trying to get data from 3 different APIs, with the same hook, which would cause them to mix up in that component during the fetching.

Now I'm using `useLazyQuery` instead, which makes it easier to query the result again on network change. 

Like this, for instance:
```javascript
const [getGoerliData, { data: goerliData }] = useLazyQuery(
    GET_ACTIVE_ITEMS_GOERLI,
  );
  const [getMumbaiData, { data: mumbaiData }] = useLazyQuery(
    GET_ACTIVE_ITEMS_MUMBAI,
  );
  const [getArbitrumGoerliData, { data: arbitrumGoerliData }] = useLazyQuery(
    GET_ACTIVE_ITEMS_ARBITRUM_GOERLI,
  );

function getAppropriateData() {
    if (network.name === 'goerli') {
      getGoerliData();
    } else if (network.name === 'maticmum') {
      getMumbaiData();
    } else if (network.name === 'arbitrum-goerli') {
      getArbitrumGoerliData();
    }
  }

useEffect(() => {
    getAppropriateData();

    if (network.name === 'goerli' && goerliData) {
      setActiveItems(goerliData?.activeItems);
    } else if (network.name === 'maticmum' && mumbaiData) {
      setActiveItems(mumbaiData?.activeItems);
    } else if (network.name === 'arbitrum-goerli' && arbitrumGoerliData) {
      setActiveItems(arbitrumGoerliData?.activeItems);
    }
  }, [network, goerliData, mumbaiData, arbitrumGoerliData]);
```

This way, when changing network, the data gets updated to the right value, but after a refresh.

Also, the previously fetched data gets also stored in the new one, even if it was not intended. For instance:
1. The user is on Goerli network, with `goerliData` containing the correct array.
2. Changing network to Mumbai will cause `getMumbaiData` to be triggered.
3. The page won't be updated, and now `mumbaiData` also gets the result of the previous query (`getGoerliData`).
4. After refreshing the page, `mumbaiData` gets the correct value, and the two other are back to `undefined`.
5. But as long as the page is not refreshed, it keeps storing the data that had been fetched the first time in each of the other one.

The solution I found was getting the `refetch` function for each one of these, and using it instead. It successfully fetches the right data without refreshing the page.

It works as intended like this:
```javascript
if (network.name === 'goerli') {
      refetchGoerliData();
      goerliData && setActiveItems(goerliData.activeItems);
    } else if (network.name === 'maticmum') {
      refetchMumbaiData();
      mumbaiData && setActiveItems(mumbaiData.activeItems);
    } else if (network.name === 'arbitrum-goerli') {
      refetchArbitrumGoerliData();
      arbitrumGoerliData && setActiveItems(arbitrumGoerliData.activeItems);
    } 
```

Hope this might help someone eventually!

**Comment by david-vendel** [comment]
Hello @polar0 
I'm not maintainer here, but I also just set up this library on my project.
You deffinitively don't need to avoid using useQuery hook, or make a complicated logic as you implemented. I am using 2 queries querying 2 different APIs in same component, next to each other. Without problems.
You need to find out what is your bug, because that should work for you seamlessly. Method I use is just to find here in github search some public project which uses this library, download it locally and carefully inspect it.

One thing I see in your query is you use decorators before query arguments, while I use after, such as:
```
query GetNodesQuery($types: [String!], $endTime: Date!) @api(name: webApp) {
  nodes(types: $types, endTime: $endTime) {
    ...NodeFragment
  }
}
```
However you are using a different approach to write queries. I just write them in .graphql files, in same format as Apollo Studio genereates them for me. Not sure if that matters.

**Comment by 0xpolarzero** [comment]
Hey @justdvl,

Thank you for your answer and for taking the time to have a look!

It is, indeed, a different way of querying, but I could find some other implementations similar to mine! I did not think about searching for public projects using it by just typing the name or some piece of code. So thanks for the tip!

There is obviously something I'm missing, that prevents me from using regular `useQuery`. I'll inspect some other implementations, and give an update here if I can find the issue!
