### ISSUE TITLE
What about multiple schemas + introspection?

### ISSUE THREAD

**Issue by seanconnollydev** [habx/apollo-multi-endpoint-link#49]
Hello, 

Thank you for publishing this link. I've faced a similar use case and implemented a similar one-off solution that works in a similar way. One thing that I have not found a solution for is the case when there are multiple endpoints _and_ we need to feed Apollo Client with some schema, i.e. with `IntrospectionFragmentMatcher`. I keep coming to the conclusion that Apollo just wants there to be _one_ schema and that solutions like yours won't stand the test of time in more complex use cases. I'm just curious if you have encountered this problem?

**Comment by jean9696** [comment]
Hi @goldenshun,
We did not face this issue because we merge our multiples schemas before with `@graphql-toolkit/schema-merging`, it works well for our cases. Does anything prevent you from doing that ?

**Comment by seanconnollydev** [comment]
Hey @jean9696, I think we could do that. I assume you are just merging the schemas from the multiple endpoints and plugging that output into `IntrospectionFragmentMatcher`. What was the main reason you chose to support multiple links in the client rather than schema stitch in your own GraphQL server and work with a single endpoint? I'm not saying you _should_ have done that, but I'm facing a similar decision and would love to know what your thought process was.

**Comment by jean9696** [comment]
For what I know, the main reason is that our architecture is micro-services and we do not want one single point of failure problem so we have chosen to keep different endpoints. But this is totally debatable.
However we would like to add a service to "merge" some query with [apollo federation](https://www.apollographql.com/docs/apollo-server/federation/introduction/), it would be another endpoint.
We wrote [an article](https://www.habx.com/tech/micro-graphql-schema) a year ago about that (which we need to rewrite).

**Comment by seanconnollydev** [comment]
Great, thanks for sharing!
