### ISSUE TITLE
Readme confusing on how to use createHttpLink

### ISSUE THREAD

**Issue by karnash** [habx/apollo-multi-endpoint-link#62]
` createHttpLink: () => new HttpLink({ ... })`
hi there i confused about this line... in special with ( ... )  mmmm.. i start with graphql and react but i don understand what must be inside there.. can help me.. thk

**Comment by jean9696** [comment]
Hi @karnash ,
we used new HttpLink but you can use createHttpLink like is shown in [apollo documentation](https://www.apollographql.com/docs/link/links/http/)

```typescript
import { createHttpLink } from "apollo-link-http";

  new ApolloClient({
    link: ApolloLink.from([
      new MultiAPILink({
          endpoints: {
              housings: 'https://housings.api',
              projects: 'https://projects.api',
              ...
          },
          createHttpLink: createHttpLink,
        }),
    ])
  })
```
You don't need to provide any param since our link adds the uri. 🙂
I updated the readme https://github.com/habx/apollo-multi-endpoint-link/commit/5f21c6c3bd83de902e6c0381ec567da4ac097750 👍

Hope this will make it clear !

**Comment by jean9696** [comment]
Readme updated here https://github.com/habx/apollo-multi-endpoint-link/commit/5f21c6c3bd83de902e6c0381ec567da4ac097750

**Comment by david-vendel** [comment]
Hello @jean9696 , in [Apollo Client doc](https://www.apollographql.com/docs/react/api/link/apollo-link-http/), they use HttpLink to create a link:
```
const link = new HttpLink({
  uri: "http://localhost:4000/graphql"
  // Additional options
});
```
My project also uses that. I don't even have `apollo-link-http` included in my node modules and prefer to keep it so. 
I tried adding apollo-link-http but it seems to require lower version of graphql (I have 16.6.0).
 
What is example configuration of this library using HttpLink?

**Comment by david-vendel** [comment]
I managed to import createHttpLink from '@apollo/client'
