### ISSUE TITLE
dynamic endpoints support

### ISSUE THREAD

**Issue by pmualaba** [habx/apollo-multi-endpoint-link#71]
I would like to use this neat library, but my multiple endpoints uris are not know upfront, some of them are, but the others are generated dynamically  on user interaction with the application. Is there a way to inject more endpoint uris as they become available?

**Comment by jean9696** [comment]
Hi @pmualaba,
We never though about this way of managing apollo links but this link behave like any other one so you should be able to create a new `ApolloClient` each time your endpoint list changes ?
Something like 
```js
const generateApolloClient = (endpoints) => new ApolloClient({
 link: ApolloLink.from([
   new MultiAPILink({
       endpoints,
       createHttpLink: () => createHttpLink(),
     }),
 ])
})
```

**Comment by jean9696** [comment]
I'm closing this issue since it's not really related to this library
